first homework Nosov
kilinochi/todo-list-mvc pull request #15
Opened 2019-03-11 18:50 UTC by JustAddAcid

Roman A. Nosov
First homework

2019-04-14 19:06 UTC, JustAddAcid commented
### Фронтенд

- Взял свою же работу по фронтенду из предыдущего семестра
- Добавил лишь XMLHTTPrequests на сервер на добавление/изменение/удаление записей в туду

Относительно красивая структура на чистом es6. Заслуженная тройка по фронтенду 
Исходники здесь -- https://github.com/JustAddAcid/es6-todo

В текущий PR поместил уже собранный вебпаком билд фронтенда. (возможно можно было сделать элегантнее, но я не знаю как)

### Сервер
Со стороны сервера добавил простейший REST-подобный API на CRUD записей в туду.

2019-04-16 10:36 UTC, androniy commented on README.md
> +- Добавил лишь XMLHTTPrequests на сервер на добавление/изменение/удаление записей в туду
Хотелось увидеть генерацию списка на сервере

2019-04-16 10:38 UTC, androniy requested changes
Хотелось увидеть генерацию списка на сервере

2019-04-30 13:52 UTC, JustAddAcid commented
Понял :) Сделаю генерацию на сервере. 

Пока прикрутил простейшую авторизацию. С базой sqlite (Да, храню пароли в базе плейн текстом, чуть позже сделаю хеши, как подобает)

Посмотрите, пожалуйста. Насколько вот такой подход в подключении через datasource и хранении sql запросов прямо в SecurityConfig плох?
```java
       auth.jdbcAuthentication().dataSource(dataSource)
            .usersByUsernameQuery("select username, password, enabled, id from users where username = ?")
```

2019-05-01 17:44 UTC, JustAddAcid commented
Добавил csrf токены, сделал наконец-то приватные туду для каждого пользователя, а не общий список.

Очень странно, что нельзя явно получить какой-нибудь уникальный userId из объекта Principal.
Поэтому в базе джойн между таблицами todos и users получается по полю юзернейм, а не userId ¯\_(ツ)_/¯

2019-05-15 12:01 UTC, JustAddAcid commented
Готово, сделал генерацию на сервере.
(опять же, фронтенд лежит в другом репо >.< )

2019-05-15 12:02 UTC, JustAddAcid commented
https://github.com/JustAddAcid/es6-todo

2019-05-15 12:51 UTC, JustAddAcid commented
В базе лежат два пользователя : 
Vasya:Vasya
Petya:Petya

2019-05-17 10:16 UTC, androniy requested changes
Не видно валидации данных ни на клиенте, ни на сервере

2019-05-22 06:27 UTC, closed without merging