Homework #2
kilinochi/todo-list-mvc pull request #29
Opened 2019-04-02 13:30 UTC by RomaSV

2019-04-16 13:08 UTC, androniy requested changes

2019-04-16 13:08 UTC, androniy commented on src/main/resources/templates/index.html
> +            <!-- JS generated -->
Хочется получить готовый список с сервера и к нему подключить AJAX операции

2019-04-22 13:43 UTC, RomaSV commented on src/main/resources/templates/index.html
> +            <!-- JS generated -->
Поправил

2019-04-23 08:27 UTC, androniy reviewed
Генерацию на сервере я вижу, но её никто не использует.
После первоначальной отрисовки идёт дополнительный AJAX запрос за данными и полная перерисовка клиента

2019-04-23 08:28 UTC, androniy requested changes
Увидел валидацию на клиенте, но необходимо паралельно делать аналогичную валидацию на сервере

2019-06-11 18:29 UTC, closed without merging