First Task Druzhinini
kilinochi/todo-list-mvc pull request #3
Opened 2019-03-09 03:18 UTC by senyast4745

2019-03-12 08:17 UTC, androniy commented on src/main/resources/templates/index.html
> +    <meta http-equiv="Content-Type" content="text\html; charset=UTF-8"/>
`text\html`некорректно

2019-04-15 21:02 UTC, senyast4745 commented
@androniy Я немного ошибся и моё дз лежит тут

2019-04-16 08:23 UTC, androniy commented
Task :compileJava FAILED

2019-04-16 08:24 UTC, androniy requested changes
Task :compileJava FAILED

2019-04-18 10:52 UTC, closed without merging