hw 3 Shamenov
kilinochi/todo-list-mvc pull request #31
Opened 2019-04-08 16:28 UTC by kilinochi

Post and get with vue and axios

2019-04-11 14:17 UTC, kilinochi commented
@androniy , проверьте

2019-04-16 09:12 UTC, androniy commented on src/main/resources/templates/index.html
> +                        <input class="todo_list_item_name" th:text="item.description" value="{text}"/>
понятно, что в таком виде это не работает

2019-04-16 09:14 UTC, androniy commented on src/main/resources/static/javascript/main.js
> +            xhr.open("GET", 'todo', true);
Вижу, что для инициализации пришлось использовать дополнительный AJAX запрос
Это не очень эффективно, намного лучше было бы разобрать существующий HTML или иметь где-то в документе сериализованную модель.

2019-04-16 09:15 UTC, androniy requested changes
thyleaf не доработает

2019-04-16 10:23 UTC, kilinochi commented
@androniy  fix thyleaf

2019-04-17 20:49 UTC, kilinochi commented
@androniy + hydration

2019-04-18 08:45 UTC, androniy approved these changes

2019-04-18 08:45 UTC, closed without merging