Hw3 tuzhilkin
kilinochi/todo-list-mvc pull request #33
Opened 2019-04-14 20:21 UTC by tuzhms

2019-04-14 20:23 UTC, tuzhms commented
JavaScript

2019-04-16 08:43 UTC, androniy commented on src/main/java/spring/Service.java
> +    @RequestMapping(value = "/add", method = RequestMethod.GET)
Использование GET допустимо только для чтения.
Все модифицирующие (создание/изменение/удаление) НЕ должны использовать GET

2019-04-16 08:44 UTC, androniy commented on src/main/resources/static/js/index.js
> +var baseUrl ='http://localhost:8080';
от такого надо избавляться, потому что нигде кроме режима разработки это использовать нельзя

2019-04-16 08:45 UTC, androniy requested changes
НЕ использовать GET для модифицирующих запросов

2019-04-18 09:17 UTC, androniy requested changes

2019-04-18 09:17 UTC, androniy commented on src/main/resources/static/js/index.js
> +function refreshList(items) {
строго говоря у тебя
1. после первоначальной загрузки происходит дополнительный ajax запрос и опять же полная перерисовка
2. на каждое изменение происходит полная перерисовка списка. стоит изменять только то, что изменено
 
Я что-то проморгал это и не отметил ранее. Даю возможность избавиться от этого, тогда получишь максимальный балл

2019-04-23 08:18 UTC, androniy reviewed
В целом - хорошо, избавился от большинства недочётов.
Излишняя перерисовка, правда всё равно присутствует в некоторых случаях (удаление отмеченных). Оценку обновлю.

2019-04-23 08:19 UTC, androniy requested changes
За валидацию хвалю, но не забывай проводить аналогичные проверки на сервере.

2019-06-11 18:29 UTC, closed without merging