HOME_WORK 3 LOGINOV
kilinochi/todo-list-mvc pull request #35
Opened 2019-04-15 19:19 UTC by LoginovArkadiy

2019-04-15 19:19 UTC, LoginovArkadiy commented
@androniy

2019-04-16 13:02 UTC, androniy requested changes

2019-04-16 13:02 UTC, androniy commented on src/main/resources/static/js/main.js
> +    let requestRead = new XMLHttpRequest();
хочется обойтись без дополнительного AJAX запроса и перерисовки HTML
непонятно зачем оно здесь

2019-05-20 16:07 UTC, androniy requested changes

2019-05-20 16:07 UTC, androniy commented on src/main/resources/static/js/main.js
> +    function replaceBadSigns(s) {
видно, что не используется

2019-05-20 16:07 UTC, androniy commented on src/main/resources/static/js/main.js
> +                        + map.get(s.charAt(i))
какая-то очень странная замена, если смотреть на `goodSigns `

2019-05-20 16:07 UTC, androniy commented on src/main/java/ru/technopolis/service/Service.java
> +        return ResponseEntity.ok(dao.create(description, auth.getName()));
на сервере надо валидировать данные так же, как и в браузере

2019-05-20 18:52 UTC, l0gark commented
@androniy, последняя версия

2019-05-21 09:36 UTC, androniy requested changes

2019-05-21 09:36 UTC, androniy commented on src/main/resources/static/js/main.js
> +    let requestRead = new XMLHttpRequest();
по факту изменений изыточная перерисовка всё ещё присутствует

2019-05-21 09:36 UTC, androniy commented on src/main/resources/static/js/main.js
> +    function addItem(description, mark) {
строго говоря, функция небезопасна с точки зрения XSS
так как не экранирует входные данные

2019-05-21 11:39 UTC, closed without merging