hw
kilinochi/todo-list-mvc pull request #36
Opened 2019-04-15 20:40 UTC by Nadenokk

2019-04-16 13:05 UTC, androniy requested changes
не вижу AJAX

2019-04-17 12:55 UTC, androniy requested changes
Всё ещё не вижу

2019-04-17 20:19 UTC, Nadenokk commented
наконец-то и я его добавила

2019-04-18 08:57 UTC, androniy approved these changes
Вижу существенный прогресс, но остались недоработки, максимальный балл не проставлю

2019-04-18 08:57 UTC, androniy commented on src/main/resources/static/script.js
> +    SendRequest("GET","/create",str, DefRequest);
Нельзя проводить изменения (создание/обновление/удаление) через HTTP метод GET

2019-04-18 08:57 UTC, androniy commented on src/main/resources/static/script.js
> +    location.reload ();
Результат создания тоже хотелось видеть без перезагрузки страницы, как сейчас происходит при обновлении/удалении

2019-04-18 08:57 UTC, closed without merging