Homework#3 Dmitriev
kilinochi/todo-list-mvc pull request #38
Opened 2019-04-16 05:22 UTC by BrainLUX

2019-04-16 12:49 UTC, androniy requested changes

2019-04-16 12:49 UTC, androniy commented on src/main/resources/public/js/index.js
> +loadToDos();
вместо загрузки хочется видеть список, сгенерированный на сервере

2019-04-16 12:52 UTC, androniy commented on src/main/resources/public/js/UI/components/TodoListComponent.js
> +        request.open('GET', '/delete?id=' + item.id, true);
Нельзя изменения проводить HTTP методом GET

2019-04-16 21:21 UTC, BrainLUX commented
@androniy fixed

2019-04-17 12:39 UTC, androniy approved these changes

2019-04-17 12:39 UTC, closed without merging