Hw4 Shamenov
kilinochi/todo-list-mvc pull request #43
Opened 2019-04-24 06:01 UTC by kilinochi

Security + validation

2019-04-25 11:08 UTC, androniy requested changes

2019-04-25 11:08 UTC, androniy commented on src/main/resources/static/javascript/main.js
> +                return;
требуется какая-то индикация ошибки

2019-04-25 11:08 UTC, androniy commented on src/main/resources/static/javascript/main.js
> +                formData.append("description", this.todo.description);
тоже требуется какая-то индикация ошибки,
более того если валидация не произошла, то обновлять запись не надо

2019-04-25 11:08 UTC, androniy commented on src/main/java/ru/technopolis/controller/WebController.java
> +        return dao.create(description);
не забываем проводить валидацию на сервере по правилам, присутствующим на клиенте

2019-04-25 11:08 UTC, androniy commented on src/main/java/ru/technopolis/config/SecurityConfig.java
> +                .csrf().disable()
Я подозреваю, что ты пошёл по "простому" пути и сделал это, чтобы заработал AJAX.
Можно пока оставить так, однако мы ещё затронем тему CSRF и придётся убрать данное отключение.

Если есть время/желание можешь ознакомиться с темой в документации https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/htmlsingle/#csrf
В частности с абзацем https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/htmlsingle/#csrf-include-csrf-token-ajax

2019-05-06 08:49 UTC, androniy requested changes

2019-05-06 08:49 UTC, androniy commented on src/main/java/ru/technopolis/model/ToDo.java
> +    @Pattern(regexp = "/[\\/\\\\\\-+<>=*@#\\$%^\\&]/")
Серверная валидация не работает. Ни размер, ни регулярка

2019-05-06 08:49 UTC, androniy commented on src/main/java/ru/technopolis/dao/ToDoDAO.java
> +    private Map<Long, ToDo> todos = new ConcurrentHashMap<>();
не видно работы с пользователем, список общий

2019-05-11 17:37 UTC, kilinochi commented
@androniy  Добавлена поддержка множества пользователей. А также, при несоблюдении валидации вылет экзепшенов в маппингах

2019-05-17 09:42 UTC, androniy approved these changes

2019-05-17 09:42 UTC, closed without merging