HW4 security + validation
kilinochi/todo-list-mvc pull request #45
Opened 2019-04-29 17:06 UTC by p-daniil

2019-05-06 09:32 UTC, androniy requested changes

2019-05-06 09:32 UTC, androniy commented on src/main/resources/public/js/UI/components/TodoListComponent.js
> +            var desc = escapeHtml(todoItem.querySelector('.todos-list_item_text').innerHTML);
Тут особо не обязательно делать экранирование HTML, а вот валидировать отсутствие описания требуется, раз мы требуем этого на создании.

2019-05-06 09:32 UTC, androniy commented on src/main/resources/public/js/utils/templatesManager.js
> +    return div.innerHTML;
Это лучше, чем ничего, но данная реализация не экранизирует " (кавычки). Если бы у тебя в шаблоне данные вставлялись в аттрибуты (к примеру, `<div title="{text}">`), то тут можно накосячить

2019-05-06 09:32 UTC, androniy commented on src/main/java/ru/Technopolis/WebSecurityConfig.java
> +        return new InMemoryUserDetailsManager(user);
Хотелось бы видеть более одного пользователя

2019-05-06 09:32 UTC, androniy commented on src/main/java/ru/Technopolis/model/ToDoDAO.java
> +    private Map<Long, ToDo> toDoMap = new LinkedHashMap<>();
а здесь видеть разные списки для разных пользователей

2019-05-06 09:32 UTC, androniy commented on src/main/java/ru/Technopolis/Service.java
> +        return dao.update(id, description, completed);
при обновлении надо валидировать описание аналогично созданию

2019-05-18 16:35 UTC, p-daniil commented on src/main/resources/public/js/UI/components/TodoListComponent.js
> +            var desc = escapeHtml(todoItem.querySelector('.todos-list_item_text').innerHTML);
Исправил

2019-05-18 16:36 UTC, p-daniil commented on src/main/resources/public/js/utils/templatesManager.js
> +    return div.innerHTML;
Добавил экранирование кавычек

2019-05-18 16:36 UTC, p-daniil commented on src/main/java/ru/Technopolis/WebSecurityConfig.java
> +        return new InMemoryUserDetailsManager(user);
Сделал

2019-05-20 12:46 UTC, androniy commented on src/main/resources/public/js/utils/templatesManager.js
> +    return div.innerHTML;
по хорошему, так и одиночные кавычки тоже надо экранировать.
но ладно, будем считать приемлемым

2019-05-20 12:47 UTC, androniy approved these changes

2019-05-20 12:47 UTC, closed without merging