authorization+validation
kilinochi/todo-list-mvc pull request #47
Opened 2019-05-13 13:02 UTC by blaackpanter

2019-05-14 07:59 UTC, androniy requested changes

2019-05-14 07:59 UTC, androniy commented on src/main/resources/static/js/index.js
> +    if (text.length > 34) {
Хочется увидеть валидацию пустых значений

2019-05-14 07:59 UTC, androniy commented on src/main/resources/static/js/index.js
> +    var description = item.querySelector('.todo-list_item-text').value;
при обновлении записи должны действовать правила валидации, аналогичные созданию

2019-05-14 07:59 UTC, androniy commented on src/main/java/ru/Technopolis/model/ToDoDAO.java
> +    private List<ToDo> list = new LinkedList<>();
хочется видеть отдельный список записей для каждого пользователя

2019-05-14 07:59 UTC, androniy commented on src/main/java/ru/Technopolis/model/ToDoDAO.java
> +        ToDo todos = new ToDo(id, description);
при создании и обновлении должна быть валидация данных, аналогичная правилам в браузере

2019-05-17 11:26 UTC, blaackpanter commented
@androniy

2019-05-17 11:29 UTC, blaackpanter commented
@androniy готово

2019-05-17 11:47 UTC, androniy approved these changes

2019-05-17 11:47 UTC, closed without merging