Authorization and security homework. Ruslan Murzin
kilinochi/todo-list-mvc pull request #48
Opened 2019-05-15 13:52 UTC by rusyamurzin

Регистрация новых пользователей не предусмотрена. Пользуйтесь теми, которые в readme.md.

2019-05-17 09:59 UTC, androniy reviewed
Что-то не видать валидации ни на клиенте, ни на сервере

2019-05-17 10:00 UTC, androniy requested changes
Что-то не видать валидации ни на клиенте, ни на сервере

2019-05-20 17:57 UTC, rusyamurzin commented
Добавил валидацию на клиент и сервер

2019-05-21 09:52 UTC, androniy approved these changes

2019-05-21 09:52 UTC, closed without merging