hw3
kilinochi/todo-list-mvc pull request #49
Opened 2019-05-15 20:50 UTC by EugSh

auth + multUser, validation, xss (функция template для создания тудушки)

2019-05-17 10:32 UTC, androniy requested changes

2019-05-17 10:32 UTC, androniy commented on src/main/resources/static/js/index.js
> +    if (text.length > 64 || text.match(reg) !== null){
на пустоту стоит тоже ругаться, при создании и редактировании

2019-05-17 10:32 UTC, androniy commented on src/main/java/ru/Technopolis/Service.java
> +    String create(@RequestParam String description, Authentication auth) {
надо добавить валидацию, аналогично правилам на клиенте

2019-05-21 17:54 UTC, EugSh commented
исправил

2019-05-24 15:13 UTC, androniy reviewed
относительно случайно обнаружил ошибку при попытке добавить `"`
рассчитываю, что справишься с исправлением

2019-05-24 15:14 UTC, androniy approved these changes

2019-05-24 15:14 UTC, closed without merging