Homework 1
kilinochi/todo-list-mvc pull request #5
Opened 2019-03-09 12:22 UTC by Dan525

2019-04-16 13:13 UTC, androniy requested changes

2019-04-16 13:13 UTC, androniy commented on src/main/resources/public/js/TodoService.js
> +export function request(url, method, callback) {
заготовку вижу, итоговую реализацию нет

2019-04-16 14:17 UTC, Dan525 commented on src/main/resources/public/js/TodoService.js
> +export function request(url, method, callback) {
доделал, немного не успевал

2019-04-17 12:48 UTC, androniy requested changes

2019-04-17 12:48 UTC, androniy commented on src/main/resources/public/js/index.js
> +readTodos();
Хочется видеть список, сгенерированный на сервере, к которому прикручена AJAX реализация создания/удаления/обновления

2019-04-17 21:05 UTC, Dan525 commented on src/main/resources/public/js/index.js
> +readTodos();
До этого был thymeleaf, потом заменил на js с ajax. Думал, что эти варианты являются альтернативой друг другу.
Теперь разобрался, стало понятно кто за что отвечает.

2019-04-18 10:16 UTC, androniy commented on src/main/resources/public/js/index.js
> +readTodos();
Отлично

2019-04-18 10:16 UTC, androniy approved these changes

2019-04-18 10:16 UTC, closed without merging