Auth | Vadim Dyahckov
kilinochi/todo-list-mvc pull request #53
Opened 2019-05-20 15:26 UTC by vaddya

2019-05-20 16:14 UTC, androniy requested changes

2019-05-20 16:14 UTC, androniy commented on src/main/java/ru/mail/polis/todos/config/SecurityConfig.java
> +        http.csrf().disable()
проверку CSRF отключать нельзя!
наоборот, требуется понять как обеспечивается базовый вариант этой зашиты

2019-05-20 19:25 UTC, vaddya commented on src/main/java/ru/mail/polis/todos/config/SecurityConfig.java
> +        http.csrf().disable()
Почитал, поправил.

2019-05-21 09:40 UTC, androniy approved these changes

2019-05-21 09:40 UTC, closed without merging