Vasileva
kilinochi/todo-list-mvc pull request #8
Opened 2019-03-09 13:11 UTC by oxovu

2019-03-12 08:30 UTC, androniy commented on src/main/resources/templates/index.html
> +    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
https://github.com/kilinochi/SpringMVC/pull/1#pullrequestreview-213236253

2019-04-01 19:15 UTC, oxovu commented
added second homework

2019-04-16 11:48 UTC, androniy requested changes

2019-04-16 11:48 UTC, androniy commented on src/main/resources/public/script.js
> +function deleteToDo(id) {
локальное тестирование говорит о нерабочем методе

2019-04-18 10:06 UTC, androniy approved these changes

2019-04-18 10:06 UTC, androniy commented on src/main/resources/public/script.js
> +    if (!item.classList.contains("__done")) {
сервер генерирует HTML без подобного класса, тут можно получить неверное представление о текущем состоянии элемента
правильным здесь было бы смотреть на аттрибут `checked`, который в итоге и поменяется

2019-04-18 10:06 UTC, closed without merging