CRUD functionality was added
kilinochi/todo-list-mvc pull request #9
Opened 2019-03-09 17:19 UTC by Lapter57

2019-04-14 19:06 UTC, Lapter57 commented
Выполнено домашнее задание по AJAX.

2019-04-16 12:13 UTC, androniy requested changes

2019-04-16 12:13 UTC, androniy commented on src/main/resources/templates/index.html
> +        <div class="todo-board"></div>
хочется видеть генерацию списка на сервере, к которому прикручиваем клиентскую часть для создания/редактирования и удаления

2019-04-17 23:50 UTC, Lapter57 commented on src/main/resources/templates/index.html
> +        <div class="todo-board"></div>
Добавил генерацию списка на сервере, к которому прикручиваем клиентскую часть для создания/редактирования и удаления.

2019-04-18 09:51 UTC, androniy approved these changes
Многое выглядит хорошо, но есть недочёты

2019-04-18 09:51 UTC, androniy commented on src/main/resources/webapp/js/constants/index.js
> +const apiUrl = "http://localhost:8080";
такое не стоит использовать, кроме среды разработки этот код не применим

2019-04-18 09:51 UTC, androniy commented on src/main/resources/webapp/js/models/TodosListModel.js
> +        this.updateListTodos();
тут получается, что у тебя после загрузки идут дополнительные запросы на сервер с целью создания "модели" (списка существующих)
этого хотелось избегать и наполнять модель на основе существующего HTML

2019-04-18 09:51 UTC, closed without merging